name: capstone
channels:
  - defaults
  - conda-forge
  - huggingface
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.1.0+cu126  
      - torchvision==0.15.0+cu126  
      - torchaudio==2.2.0  
      - transformers==4.28.1
      - peft==0.3.0
      - datasets==2.12.0
      - tqdm==4.64.1
      - nltk==3.8.1
      - evaluate==0.4.0
      - fastapi==0.95.0  
      - pydantic==1.10.9  
      - uvicorn==0.22.0 
  - cudatoolkit=12.6  
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip:
      - json  
